### PR TITLE
Add rpi pico

### PR DESCRIPTION
**Pull request by ernstdevreede**
I like this wrapper library very much.
Very easy to make ports.
This is a port for the Raspberry Pi Pico.

### CODE REVIEW

**Comment by lnlp** [comment]
Hi @ernstdevreede,
Thanks for your contribution.

I already have support for the Raspberry Pi Pico prepared but it does not yet compile successfully on Windows.
I suspect that there are still issues in the Arduino-mbed core and/or PlatformIO's support for it.
For instance the standard SDA and SCL pins are not defined in the pin definitions, which to me is a clear sign that it is not yet production ready.

Have you only added the support for the Pico to LMIC-node in your PR or have you actually successfully tested it?
If latter that would mean that it runs successfully on Linux (or Mac?) but not yet on Windows.

I noticed that you left out SDA and SCL definitions in your PR and used the standard I2C pins for RST and DIO0. The I2C pins should not be used however to keep them available for display and other I2C devices.

I'm interested if you actually have LMIC-node succesfully running on the Pico and what OS your are using.

Thanks

**Comment by ernstdevreede** [comment]
I changed the DIO0 and DIO1 pins to free the I2C port and added the I2C pins (6,7) in the board file.
Tested this configuration with (too small) I2C display.


This was all done on a Linux machine; haven't tested this on a Windows machine.
The platformio support for Pico is the official version from PlatformIO
pico

**Comment by lnlp** [comment]
Thanks.

I will try it on Linux (but will have to set it up first.

Apparently there is yet some work to do for Arduino-embed and/or PlatformIO's support of it.

**Comment by lnlp** [comment]
I had similar issues on Linux as on Windows.
I used `pico.h` as name for the pico BSF and it turned out that the Arduino-mbed core uses a header file with exactly the same filename and exactly the same header guard name. Changing only the header guard name showed to be insufficient.
I changed the name of the pico BSF file and after that compilation went fine.
Support for the Raspberry Pi Pico board has been added.

**Pull request closed without merging**
